services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wita
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgres/wita
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes


  ## docker-compose up stripe-cli para conseguir a secret do webhook
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli-local
    command: listen --forward-to http://host.docker.internal:8080/payments/webhook
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata: